# Docker compose to have Zookeeper, Kafka, and Kafka Manager running for development.
version: '3'
services:
  zookeeper:
    image: 3dsinteractive/zookeeper:3.4.6
    container_name: playwithkafka-zookeeper  
    ports:
      - "2181:2181"
  kafka:
    image: 3dsinteractive/kafka:1.1.0
    container_name: playwithkafka-kafka  
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    environment:
      # Need export HOST_IP_ADDRESS=$(ipconfig getifaddr $(route -n get default|awk '/interface/ { print $2 }'))
      KAFKA_ADVERTISED_HOST_NAME: "${HOST_IP_ADDRESS}"
      KAFKA_CREATE_TOPICS: "playwithkafka:3:3"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    # volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock
  kafka-manager:
    image: 3dsinteractive/kafka-manager:1.3.1.8
    container_name: playwithkafka-kafka-manager
    ports:
      - "9000:9000"
    links:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=tr
